/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author n18dc
 */
public class ChiTietVe extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietVe
     */
    public ChiTietVe(String ma, String ngay, String gio, String loaiXe, String ghe, String tram, String gia, String trangThai) {
        initComponents();
        lbMa.setText(ma);
        lbNgay.setText(ngay);
        lbGio.setText(gio);
        lbLoaiXe.setText(loaiXe);
        lbGhe.setText(ghe);
        lbTram.setText(tram);
        lbGia.setText(gia);
        lbTrangThai.setText(trangThai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbMa = new javax.swing.JLabel();
        lbGio = new javax.swing.JLabel();
        lbLoaiXe = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        lbTram = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbGhe = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbTrangThai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nhà xe phần mềm 18");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(180, 10, 270, 50);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Giá vé:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(370, 410, 60, 22);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Hân hạnh phục vụ tuyến đường TP.HCM- Đồng nai");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(80, 60, 470, 27);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(20, 100, 560, 10);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Vé Xe Vip");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(250, 120, 130, 31);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Giờ:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(360, 260, 40, 22);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ngày:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(80, 260, 50, 22);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Trạm khởi hành:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 410, 140, 22);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Loại xe:");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(70, 340, 70, 22);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 550, 110, 40);

        lbMa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbMa.setForeground(new java.awt.Color(255, 255, 255));
        lbMa.setText("MÃ");
        jPanel1.add(lbMa);
        lbMa.setBounds(320, 180, 170, 22);

        lbGio.setBackground(new java.awt.Color(204, 223, 235));
        lbGio.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lbGio.setText(" ");
        lbGio.setOpaque(true);
        jPanel1.add(lbGio);
        lbGio.setBounds(430, 250, 140, 40);

        lbLoaiXe.setBackground(new java.awt.Color(204, 223, 235));
        lbLoaiXe.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lbLoaiXe.setOpaque(true);
        jPanel1.add(lbLoaiXe);
        lbLoaiXe.setBounds(160, 330, 140, 40);

        lbNgay.setBackground(new java.awt.Color(204, 223, 235));
        lbNgay.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lbNgay.setText(" ");
        lbNgay.setOpaque(true);
        jPanel1.add(lbNgay);
        lbNgay.setBounds(160, 250, 140, 40);

        lbTram.setBackground(new java.awt.Color(204, 223, 235));
        lbTram.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lbTram.setText(" ");
        lbTram.setOpaque(true);
        jPanel1.add(lbTram);
        lbTram.setBounds(160, 400, 140, 40);

        lbGia.setBackground(new java.awt.Color(204, 223, 235));
        lbGia.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbGia.setText(" ");
        lbGia.setOpaque(true);
        jPanel1.add(lbGia);
        lbGia.setBounds(430, 400, 140, 40);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Mã vé:");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(260, 180, 53, 22);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Vị trí ghế:");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(340, 340, 90, 22);

        lbGhe.setBackground(new java.awt.Color(204, 223, 235));
        lbGhe.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lbGhe.setOpaque(true);
        jPanel1.add(lbGhe);
        lbGhe.setBounds(430, 330, 140, 40);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Trạng thái vé:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(30, 480, 110, 22);

        lbTrangThai.setBackground(new java.awt.Color(204, 223, 235));
        lbTrangThai.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbTrangThai.setText(" ");
        lbTrangThai.setOpaque(true);
        jPanel1.add(lbTrangThai);
        lbTrangThai.setBounds(160, 470, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showMessageDialog(rootPane, "Mua vé thành công");
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChiTietVe().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbGhe;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGio;
    private javax.swing.JLabel lbLoaiXe;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbTram;
    private javax.swing.JLabel lbTrangThai;
    // End of variables declaration//GEN-END:variables
}
