/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author n18dc
 */
public class PnDangKy extends javax.swing.JPanel {

    /**
     * Creates new form PnDangKy
     */
    public PnDangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtCMT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbHo = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbDangKy = new javax.swing.JLabel();
        psMatkhau1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        rBtnNam = new javax.swing.JRadioButton();
        rBtnNu = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        lbBackgroundDky = new javax.swing.JLabel();

        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Đăng Ký Khách Hàng");
        add(jLabel4);
        jLabel4.setBounds(130, 30, 210, 32);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Họ Tên:");
        add(jLabel7);
        jLabel7.setBounds(10, 180, 60, 16);

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        add(txtTen);
        txtTen.setBounds(10, 210, 217, 42);

        txtCMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMTActionPerformed(evt);
            }
        });
        add(txtCMT);
        txtCMT.setBounds(10, 320, 217, 42);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tài Khoản:");
        add(jLabel8);
        jLabel8.setBounds(10, 300, 62, 16);

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        add(txtSDT);
        txtSDT.setBounds(10, 90, 217, 42);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SĐT:");
        add(jLabel9);
        jLabel9.setBounds(10, 70, 30, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mật khẩu:");
        add(jLabel10);
        jLabel10.setBounds(10, 420, 70, 16);

        lbHo.setForeground(new java.awt.Color(255, 153, 204));
        lbHo.setText("Vui lòng nhập CMT.");
        lbHo.setVisible(false);
        add(lbHo);
        lbHo.setBounds(20, 370, 112, 16);

        lbTen.setForeground(new java.awt.Color(255, 153, 204));
        lbTen.setText("Vui lòng nhập Tên.");
        lbTen.setVisible(false);
        add(lbTen);
        lbTen.setBounds(10, 260, 108, 16);

        lbEmail.setForeground(new java.awt.Color(255, 153, 204));
        lbEmail.setText("Vui lòng nhập SĐT");
        lbEmail.setVisible(false);
        add(lbEmail);
        lbEmail.setBounds(10, 140, 107, 16);

        lbMatKhau.setForeground(new java.awt.Color(255, 153, 204));
        lbMatKhau.setText("Vui lòng nhập Mật khẩu.");
        lbMatKhau.setVisible(false);
        add(lbMatKhau);
        lbMatKhau.setBounds(12, 489, 138, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Từ 6 đến 50 ký tự");
        add(jLabel12);
        jLabel12.setBounds(12, 508, 102, 16);

        lbDangKy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbDangKy.setForeground(new java.awt.Color(51, 51, 255));
        lbDangKy.setText("Đăng nhập");
        lbDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangKyMouseClicked(evt);
            }
        });
        add(lbDangKy);
        lbDangKy.setBounds(150, 630, 87, 20);
        add(psMatkhau1);
        psMatkhau1.setBounds(12, 440, 217, 42);
        add(jSeparator3);
        jSeparator3.setBounds(100, 640, 50, 10);
        add(jSeparator4);
        jSeparator4.setBounds(240, 640, 50, 10);

        rBtnNam.setText("Nam");
        rBtnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnNamActionPerformed(evt);
            }
        });
        add(rBtnNam);
        rBtnNam.setBounds(260, 210, 55, 25);

        rBtnNu.setText("Nữ");
        add(rBtnNu);
        rBtnNu.setBounds(330, 210, 45, 25);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Giới Tính");
        add(jLabel11);
        jLabel11.setBounds(260, 190, 50, 16);

        lbGioiTinh.setForeground(new java.awt.Color(255, 153, 204));
        lbGioiTinh.setText("Vui lòng chọn giới tính");
        lbGioiTinh.setVisible(false);
        add(lbGioiTinh);
        lbGioiTinh.setBounds(260, 240, 126, 16);

        btnDangKy.setBackground(new java.awt.Color(0, 0, 255));
        btnDangKy.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        add(btnDangKy);
        btnDangKy.setBounds(90, 550, 220, 50);

        lbBackgroundDky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBackground/backgroundDky.png"))); // NOI18N
        add(lbBackgroundDky);
        lbBackgroundDky.setBounds(0, 0, 420, 690);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        boolean ktTen=false,ktGT=false, ktCMT=false, ktSDT=false, ktMK=false;
        // KT Nhập họ tên
        if(txtTen.getText().isEmpty()){
            ktTen=true;
            lbTen.setVisible(true);
            txtTen.setBorder(BorderFactory.createLineBorder(Color.red));
        }
        else if(!txtTen.getText().isEmpty()) {
            lbTen.setVisible(false);
            txtTen.setBorder(BorderFactory.createLineBorder(null));

        }

        //KT nhập Gioi Tinh
        if(!rBtnNam.isSelected() && !rBtnNu.isSelected()){
            ktGT=true;
            lbGioiTinh.setVisible(true);
        }
        else {
            lbGioiTinh.setVisible(false);
        }

        //KT nhập CMND
        if(txtCMT.getText().isEmpty()||txtCMT.getText().matches("[0-9]{9}")){
            ktCMT=true;
            lbHo.setVisible(true);
            txtCMT.setBorder(BorderFactory.createLineBorder(Color.red));
        }
        else if(!txtCMT.getText().isEmpty()) {
            lbHo.setVisible(false);
            txtCMT.setBorder(BorderFactory.createLineBorder(null));
        }

        // KT nhập sđt
        if( !txtSDT.getText().matches("0\\d{9,10}")){
            ktSDT=true;
            lbEmail.setVisible(true);
            txtSDT.setBorder(BorderFactory.createLineBorder(Color.red));
        }
        else if(txtSDT.getText().matches("0\\d{9,10}")) {
            lbEmail.setVisible(false);
            txtSDT.setBorder(BorderFactory.createLineBorder(null));
        }

        // KT nhập mật khẩu
//        if(psMatkhau.getText().isEmpty()){
//            ktMK=true;
//            lbMatKhau.setVisible(true);
//            psMatkhau.setBorder(BorderFactory.createLineBorder(Color.red));
//        }
//        else if(!psMatkhau.getText().isEmpty()) {
//            lbMatKhau.setVisible(false);
//            psMatkhau.setBorder(BorderFactory.createLineBorder(null));
//        }
//        if( ktSDT && ktMK){
//            JOptionPane.showConfirmDialog(this, "ko đc");
//
//        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void rBtnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnNamActionPerformed

    private void lbDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangKyMouseClicked
        // TODO add your handling code here:
//        pnDKY.setVisible(false);
//        pnLogin.setVisible(true);
    }//GEN-LAST:event_lbDangKyMouseClicked

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtCMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMTActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbBackgroundDky;
    private javax.swing.JLabel lbDangKy;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTen;
    private javax.swing.JPasswordField psMatkhau1;
    private javax.swing.JRadioButton rBtnNam;
    private javax.swing.JRadioButton rBtnNu;
    private javax.swing.JTextField txtCMT;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
