/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Form.QLNhanVien;
import KetNoiSQL.KetNoi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hoang
 */
public class ThemNV extends javax.swing.JFrame {

    /**
     * Creates new form ThemNV
     */
    public ThemNV() {
        initComponents();
        jLabel_maNV.setText(maNV(jComboBox_ChucVu.getSelectedItem().toString()));
    }

    // Hàm Tự Tạo Mã Nhân Viên Mới
    public String maNV(String chucVu) {
        Connection ketNoi = KetNoi.layKetNoi();
        String sql = "select * from NHAN_VIEN order by MaNV DESC";
        String maNVmoi = "";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                if(rs.getString(6).equals(chucVu)){
                    maNVmoi = rs.getString(1);
                    break;
                }
            }

            ps.close();
            ketNoi.close();
        } catch (SQLException e) {
            Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, e);
        }
        
        if(Integer.parseInt(maNVmoi.substring(2)) < 10){
            int maSo = Integer.parseInt(maNVmoi.substring(2)) + 1;
            String maChu = maNVmoi.substring(0,2);
            maNVmoi = maChu + "0" +String.valueOf(maSo);
        }else{
            int maSo = Integer.parseInt(maNVmoi.substring(2)) + 1;
            String maChu = maNVmoi.substring(0,2);
            maNVmoi = maChu +  String.valueOf(maSo);
        }
        
        return maNVmoi;
    }
    
    
    public void themNhanVien(String maNV, String hoTen, String CMND, String gioiTinh,String dienThoai, String chucVu) {
        Connection ketNoi = KetNoi.layKetNoi();
        String sql = "insert into NHAN_VIEN values (?,?,?,?,?,?,?)";

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, maNV);
            ps.setString(2, hoTen);
            ps.setString(3, CMND);
            ps.setString(4, gioiTinh);
            ps.setString(5, dienThoai);
            ps.setString(6, chucVu);
            ps.setString(7, null);
            ps.executeUpdate();
            
            ps.close();
            ketNoi.close();
        } catch (SQLException e) {
            Logger.getLogger(ThemNV.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_tenNV = new javax.swing.JTextField();
        jTextField_SDT = new javax.swing.JTextField();
        jTextField_CMND = new javax.swing.JTextField();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox_ChucVu = new javax.swing.JComboBox<>();
        jLabel_maNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Mã Nhân Viên :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Tên Nhân Viên :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("CMND : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Chức Vụ : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Điện Thoại : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Giới Tính");

        jTextField_tenNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField_SDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jTextField_CMND.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        buttonGroup1.add(jRadioButton_Nam);
        jRadioButton_Nam.setText("Nam");

        buttonGroup1.add(jRadioButton_Nu);
        jRadioButton_Nu.setText("Nữ");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "NV bán vé", "Tài Xế" }));
        jComboBox_ChucVu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ChucVuItemStateChanged(evt);
            }
        });
        jComboBox_ChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_ChucVuMouseClicked(evt);
            }
        });

        jLabel_maNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel_maNV.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_maNV.setText("Mã Nhân Viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_maNV)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_CMND, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_tenNV, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(46, 46, 46)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton_Nam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton_Nu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_maNV))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton_Nam)
                    .addComponent(jRadioButton_Nu))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String maNV, hoTen, CMND, gioiTinh, dienThoai, chucVu;
        if (jTextField_tenNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Điền Tên Nhân Viên");
        } else if (jTextField_CMND.getText().isEmpty() || !jTextField_CMND.getText().matches("[0-9]{9}")) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Xem Lại CMND");
        } else if (!jRadioButton_Nu.isSelected() && !jRadioButton_Nam.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Giới Tính");
        } else if (!jTextField_SDT.getText().matches("0\\d{9,10}") || jTextField_SDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Xem Lại SDT");
        }else{
            maNV = jLabel_maNV.getText();
            hoTen = jTextField_tenNV.getText();
            CMND = jTextField_CMND.getText();
            if(jRadioButton_Nam.isSelected()){
                gioiTinh = jRadioButton_Nam.getText();
            }
            else{
                gioiTinh = jRadioButton_Nu.getText();
            }
            dienThoai = jTextField_SDT.getText();
            chucVu = jComboBox_ChucVu.getSelectedItem().toString();
            themNhanVien(maNV, hoTen, CMND, gioiTinh, dienThoai, chucVu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_ChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_ChucVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ChucVuMouseClicked

    private void jComboBox_ChucVuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ChucVuItemStateChanged
        // TODO add your handling code here:
        jLabel_maNV.setText(maNV(jComboBox_ChucVu.getSelectedItem().toString()));
    }//GEN-LAST:event_jComboBox_ChucVuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_ChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_maNV;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JTextField jTextField_CMND;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_tenNV;
    // End of variables declaration//GEN-END:variables
}
